DELETE FROM MOVIE;
DELETE FROM MYUSER;
DELETE FROM RAT;
DELETE FROM PAYMENT;
DELETE FROM MOVIE_PAYMENT;
DELETE FROM SNACK_INFO;
DELETE FROM MYUSER_SNACK_ORDER;

DELETE FROM EMPLOYEE_TASK;
DELETE FROM EMPLOYEE;
DELETE FROM AD;
DELETE FROM MOVIE_AD;
DELETE FROM ACTOR;
DELETE FROM MOVIE_ACTOR;
DELETE FROM PAYMENT_STATICS;
COMMIT;

/*SELECT * FROM MOVIE_ACTOR;
SELECT * FROM RAT;
SELECT * FROM MOVIE;
SELECT * FROM PAYMENT;
SELECT * FROM MOVIE_PAYMENT;
SELECT * FROM SNACK_INFO;
SELECT * FROM MYUSER_SNACK_ORDER;

SELECT * FROM EMPLOYEE_TASK;
SELECT * FROM EMPLOYEE;
SELECT * FROM AD;
SELECT * FROM MOVIE_AD;
SELECT * FROM ACTOR;
SELECT * FROM MOVIE_ACTOR;
SELECT * FROM PAYMENT_STATICS;

*/

 exec reset_sequence('movie_payment_inc');
 exec reset_sequence('employee_inc');
 exec reset_sequence('movie_ad_inc');
 exec reset_sequence('snack_order_inc');
 
select * from movie_ad;
select * from myuser_snack_order;
select * from employee;
select * from movie_payment;